// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ep8zc9ywAZNSVCCzIn5uibYi6cXLVJA',
    appId: '1:690401271468:web:afc3ebd7893a04db848909',
    messagingSenderId: '690401271468',
    projectId: 'cpm-system',
    authDomain: 'cpm-system.firebaseapp.com',
    storageBucket: 'cpm-system.appspot.com',
    measurementId: 'G-WWGH276MQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxCq92aEZhiGJy2KwBQ8LNmCw_qPHhPg',
    appId: '1:690401271468:android:5fc153d44558b5a0848909',
    messagingSenderId: '690401271468',
    projectId: 'cpm-system',
    storageBucket: 'cpm-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYRBIpE8HzkTPhaeNgEwltMsVsotjgR4',
    appId: '1:690401271468:ios:9fdf527adced589a848909',
    messagingSenderId: '690401271468',
    projectId: 'cpm-system',
    storageBucket: 'cpm-system.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYRBIpE8HzkTPhaeNgEwltMsVsotjgR4',
    appId: '1:690401271468:ios:9fdf527adced589a848909',
    messagingSenderId: '690401271468',
    projectId: 'cpm-system',
    storageBucket: 'cpm-system.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ep8zc9ywAZNSVCCzIn5uibYi6cXLVJA',
    appId: '1:690401271468:web:29804c0bfd6eafbc848909',
    messagingSenderId: '690401271468',
    projectId: 'cpm-system',
    authDomain: 'cpm-system.firebaseapp.com',
    storageBucket: 'cpm-system.appspot.com',
    measurementId: 'G-2X8QJ1R48E',
  );
}
